### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by JipDol2** [hyh1016/operation-together#76]
안녕하세요.

재밌어 보이는 프로젝트 같아 저도 한번 참여를 해보고 싶은데 혹시 가능할까요?

큰 부분은 건드리지 않고 코드를 해석하고 공부하는 방식으로 참여를 해보고 싶습니다.

가능하다면 어떻게 정상적으로 실행을 할 수 있는지 알려주시면 감사하겠습니다.

감사합니다.

**Comment by hyh1016** [comment]
안녕하세요 @JipDol2님! 우선 제 프로젝트를 좋게 봐 주셔서 감사하다는 말씀을 먼저 드리고 싶네요 😄 정말 감사합니다

해당 프로젝트에서는 db config 관련 정보, jwt secret 등과 같이 외부에 노출되면 안 되는 프로퍼티들을 별도로 [application-secret.properties](https://github.com/hyh1016/operation-together/blob/dev/src/main/resources/application-secret.properties)에서 관리하고 있습니다! 아마 해당 내용들을 @JipDol2님의 로컬 환경에 맞춰 구성하시면 정상적으로 실행이 될 거라고 생각됩니다 :)

저도 이제 막 스프링을 공부하기 시작한 입장이라 코드가 깔끔하지 못할 수도 있지만 많은 도움이 되셨으면 좋겠습니다.
피드백 등은 언제나 환영입니다! 감사합니다 👍

**Comment by JipDol2** [comment]
@hyh1016 
local server 에 띄우는거 성공했습니다. ㅎㅎㅎ 너무 재밌네요. 저가 jwt 에 관한 지식이 없어서 이부분에 대해선 좀 더 학습을 해야될 것 같습니다.

혹시 application.properties 를 yml 파일로 안하신 이유가 따로 있으실까요???
