### ISSUE TITLE
[error]Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.

### ISSUE THREAD

**Issue by JipDol2** [hyh1016/operation-together#80]
안녕하세요.
열심히 @hyh1016 님의 프로젝트를 확장해가는 도중에 제목과 같은 에러가 발생하였습니다.
처음 프로젝트를 받고 난 후에 사용했을시에는 전혀 발생하지 않았던 에러였는데 
OperationRepository 에서 @Query 어노테이션에 findByLink 메소드에서 에러가 발생하였습니다.

구글링 한 결과 java 8버전이상에서는 @Param 어노테이션을 이용하던지 -parameters 를 이용해라 라는 에러메세지여서 @Param 어노테이션을 붙여준 결과 해결할 수 있었습니다.
```
@Query("SELECT o FROM Operation o WHERE o.link=:link")
public Optional<Operation> findByLink(@Param("link") String link);
```

혹시 이런 에러를 만났던 경험이 있으신지 궁금합니다.
감사합니다.

**Comment by JipDol2** [comment]
https://www.inflearn.com/questions/367372

아마 -paramters 옵션이 gradle 을 통해 들어갔던걸 제가 수정하면서 생긴 오류 같습니다.
공식문서에서도 사용하는 것을 보니 @Param 어노테이션을 사용하는 것이 맘편하겠네요 ㅎㅎ 

감사합니다!!

**Comment by hyh1016** [comment]
오오.. 막연히 변수명과 일치하면 생략해도 되는 부분인 줄로만 알았는데,
gradle이 알아서 처리해 주는 부분을 명확히 알고 있는 것도 중요할 것 같네요! 😂
좋은 정보 공유해주셔서 감사합니다 👍👍
