### ISSUE TITLE
spring Interceptor 를 도입했을 경우 발생하는 문제점

### ISSUE THREAD

**Issue by JipDol2** [hyh1016/operation-together#81]
안녕하세요.
로그인 기능을 구현해보려고 시도 중입니다.
그러나 spring Interceptor를 구현하는 과정에서 풀리지 않는 문제점이 발생하여 이렇게 이슈를 남깁니다.

작전을 생성하는 페이지는 로그인을 성공한 유저에게만 허용하게끔 하기 위해 '인증/인가' 기능을 Interceptor로 구현하려고 하였습니다.

즉, interceptor에서 token을 가지고 있다면 로그인이 된 유저라고 판단 가지고 있지 않다면 로그인을 아직 하지 않는 유저라고 판단하고,
token을 가지고 있지 않는 상태에서 권한인증이 필요한 페이지에 접근하려고 하였을땐 exception을 발생시키게끔 구현하였습니다.

그러나 단순 페이지 이동시에 문제가 발생하게 되었습니다. 
@hyh1016 님이 구현하신 소스를 보면 페이지간 이동시에는 `location.href` 를 이용하셨던데 이렇게 해버리니 token 값을 http 통신을 사용하여 함께 서버로 전송하지 못하는 현상이 발생하였습니다.

그래서 그냥 Interceptor를 사용하지 않고 권한 처리는 이미 구현되어 있는 JwtFilter를 사용하여 확인해준다음, 정상코드를 리턴받으면 페이지 이동, 아니라면 `login` 페이지로 이동하게끔 해주었습니다.

근데 여기서 또다른 문제점이 발생하였는데 바로 **프론트의 동작**에서 페이지에 접근하는 것이 아니라 `url`을 통해서 접근하려고 했을때 막을 방법이 업어진 것입니다....
`ex) localhost://8080/operation/`

그래서 결국 이러지도 못하고 저러지도 못하는 상황에서 많은 시간이 소묘됐고 도움을 받고 싶어서 이렇게 글을 올립니다.

감사합니다.

**Comment by JipDol2** [comment]
해결했습니다.

인가받은 사용자만 특정 페이지에 접속할 수 있게끔 해주기 위해 전 처음에 무조건 그 특정 페이지가 로딩 되기 전에 사전에 차단해야 된다고 생각했습니다.

그러다 보니 인터셉터와 화면전환시 데이터를 포함하는 기능 사이에서 합의점을 찾지 못한 문제점이 발생했었습니다.

그러나 여기저기 물어보고 찾아본 결과 특정 페이지가 로딩된 후에 js 파일을 실행하여 토큰을 가지고 있는지 체크한 후 없다면 로그인 창으로 자동으로 이동하게끔 하는 방법으로 기능을 확장할 수 있게 되었습니다.

감사합니다!

**Comment by hyh1016** [comment]
확인하였습니다! 👍

저는 해당 프로젝트에서는 쉬운 사용과 접근성 쪽에 초점을 맞춰 로그인 기능을 도입하지 않기로 결정했어서, 작전 비밀번호 인증에 한해서만 인증 기능을 구현하고 Filter의 개념도 학습하자는 취지로 JwtFilter를 구현했습니다!

사실 저는 나중에 여유가 생기면 프론트를 React로 따로 분리할 예정이라서, auth 관련 controller 쪽은 이 때 한번 리팩토링을 거치게 될 것 같습니다. 😂

그래서 아마 인증 부분 코드는 완성도가 많이 떨어져서, 로그인 기능을 도입하고자 하신다면 JwtFilter 부분을 아예 제거하시고 인증 기능 관련해서 리팩토링을 진행해보셔도 좋을 것 같네요 😀

감사합니다. 오늘도 즐거운 코딩 되세요!
